name: Github Release

on:
  workflow_call:

jobs:
  github-release:
      name: Github Release
      runs-on: ubuntu-latest
     
      steps:
        - uses: actions/download-artifact@v2
          with:
            name: url

        - id: releaseprep
          run: |
            cat >$CHANGELOG <<-EOD
            Release ${GITHUB_REF#refs/tags/}
            Download available:
            EOD
            cat url-* >> $CHANGELOG
          env:
            CHANGELOG: release.txt

        - name: Release
          uses: softprops/action-gh-release@v1
          with:
            body_path: release.txt
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
