name: Release

on:
  push:
    tags:
      - '*'
    repository_dispatch:
      types: [whitelabel-update]
      
  release:
    types: [created]

jobs:
  name: Update tags
  
  runs-on: ubuntu-latest
  
  steps:
    - name: Get latest tag
      run: echo "$(git describe --tags `git rev-list --tags --max-count=1`)"
  
