name: Release

on:
  push:
    tags:
      - '*'
    branches: [main]
  repository_dispatch:
    types: [whitelabel-update]
      
  release:
    types: [created]

# name: Generate
jobs:
  generate:
    runs-on: ubuntu-latest
    name: generate
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0 # Optional fallback tag to use when no tag can be found
      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - name: 'Create new milestone'
        id: createmilestone
        uses: "WyriHaximus/github-action-create-milestone@v1"
        with:
          title: ${{ steps.semvers.outputs.patch }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
#   get_tag:
#     name: Update Tags
# #     needs: set_tag
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Get Latest Tag
# #         run: echo "${{needs.set_tag.outputs.latest_tag}}"
#         run: echo "$(git describe --tags `git rev-list --tags --max-count=1`)"

